# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ESX' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ESX
  pod 'RNMobileCenter', '~> 0.2.0'
  pod 'MobileCenter', '~> 0.4.0'

  

  target 'ESXTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ESX-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ESX-tvOS

  target 'ESX-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
