target 'EXApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tonypoc
  pod 'RNMobileCenter', '~> 0.2.0'
  pod 'MobileCenter', '~> 0.4.0'
end

# Auth0 Lock

pod 'Lock', '~> 1.26'
pod 'Lock/TouchID'
pod 'Lock/SMS'
pod 'Lock/Email'
